platform :ios, '10.0'

target 'ARWithLocationTask' do

  pod 'GooglePlacePicker', '~> 2.5'
  use_frameworks!

  # Pods for ARWithLocationTask

  target 'ARWithLocationTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARWithLocationTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
